---
title: Pavel's block
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
    layout: post
  reviews:
    title: Reviews
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
baseurl: 
subtitle: Some random thoughts
author: Pavel Popov
description: |-
  Personal block(g) of Pavel Popov containing his thoughts, experiments and projects.

  And TILs.
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
permalink: "/articles/:short_year/:title"
excerpt_separator: "<!--more-->"
exclude:
- README.md
