---
title: Pavel's block
timezone: Europe/Moscow
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
subtitle: just some random thoughts
author: pavel popov
simple_search: http://google.com/search
description: |-
  Personal block(g) of Pavel Popov containing his thoughts, experiments and projects.

  And TILs.
name: Pavel's block
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
permalink: "/articles/:short_year/:title"
excerpt_separator: "<!--more-->"
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- UploadToGithub.Rakefile
- README.md
post:
  template: _post.txt
  extension: markdown
page:
  template: _page.txt
  extension: markdown
git:
  branch: master
