---
title: Pavel's block
collections:
  posts:
    title: Posts
    output: true
    layout: post
  reviews:
    title: Reviews
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
baseurl:
author: Pavel Popov
description: |-
  Personal blog of Pavel Popov containing his thoughts, experiments and projects.

  And TILs.
markdown: kramdown
markdown_ext: markdown,md
permalink: "/post/:title"
excerpt_separator: "<!--more-->"
exclude:
- README.md
