---
title: Pavel's block
collections:
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
baseurl:
author: Pavel Popov
description: |-
  Personal blog of Pavel Popov containing his thoughts, experiments and projects.

  And TILs.
markdown_ext: markdown,md
permalink: "/post/:title"
excerpt_separator: "<!--more-->"
exclude:
- README.md
- "*.sh"
- "theme/"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
